CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;

CREATE TABLE amounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_info_id bigint NOT NULL,
    amount bigint NOT NULL,
    CONSTRAINT pk_amounts PRIMARY KEY (id)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230714032450_InitialCreate', '7.0.9');

COMMIT;

START TRANSACTION;

ALTER TABLE users DROP CONSTRAINT pk_users;

ALTER TABLE amounts DROP CONSTRAINT pk_amounts;

ALTER TABLE users RENAME TO user_info;

ALTER TABLE amounts RENAME TO user_amount;

ALTER TABLE user_info ADD CONSTRAINT pk_user_info PRIMARY KEY (id);

ALTER TABLE user_amount ADD CONSTRAINT pk_user_amount PRIMARY KEY (id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230714032933_2', '7.0.9');

COMMIT;

START TRANSACTION;

ALTER TABLE user_amount ALTER COLUMN user_info_id DROP NOT NULL;

CREATE INDEX ix_user_amount_user_info_id ON user_amount (user_info_id);

ALTER TABLE user_amount ADD CONSTRAINT fk_user_amount_user_info_user_info_id FOREIGN KEY (user_info_id) REFERENCES user_info (id);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230714033155_3', '7.0.9');

COMMIT;

START TRANSACTION;

ALTER TABLE user_info ALTER COLUMN name TYPE character varying(128);

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20230714033401_4', '7.0.9');

COMMIT;
